services:
  web:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: "http://localhost:8080/api/v1"
    image: meli-frontend:latest
    ports:
      - "5173:80"
    depends_on:
      - api
    restart: unless-stopped